spring:
  flyway:
    locations: 'classpath:db/migrations'
    table: schema_version
    baseline-on-migrate: true
    url: jdbc:h2:file:./h2/productData
    user: test
    password: password
    default-schema: PUBLIC
    clean-disabled: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./h2/productData;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle;NON_KEYWORDS=USER;
    username: test
    password: password
    hikari:
      connection-timeout: 45000
      maximum-pool-size: 3
      minimumIdle: 1
      idleTimeout: 450000
      maxLifetime: 2400000
