spring:
  flyway:
    locations: 'classpath:db/migrations'
    table: schema_version
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./h2/productData;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle;DEFAULT_NULL_ORDERING=HIGH
    username: test
    password: password
    hikari:
      connection-timeout: 45000
      maximum-pool-size: 3
      minimumIdle: 1
      idleTimeout: 450000
      maxLifetime: 2400000
