CREATE TABLE PRODUCT (
    ID          NUMBER(10) PRIMARY KEY,
    NAME        VARCHAR(200),
    EXTERNAL_ID VARCHAR(200) UNIQUE NOT NULL,
    PRICE       NUMBER(10, 2),
    CREATED_AT  TIMESTAMP WITH TIME ZONE,
    MODIFIED_AT TIMESTAMP WITH TIME ZONE
);

CREATE SEQUENCE S_PRODUCT_0;