CREATE TABLE PRODUCT
(
    ID          NUMBER(10) PRIMARY KEY,
    NAME        VARCHAR2(200 CHAR),
    EXTERNAL_ID VARCHAR2(500 CHAR),
    PRICE       NUMBER(10, 2),
    CREATED_AT  TIMESTAMP WITH TIME ZONE,
    MODIFIED_AT TIMESTAMP WITH TIME ZONE
);

CREATE SEQUENCE S_PRODUCT_0;